// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskList_Server.Data;


#nullable disable

namespace TaskList_Server.Migrations
{
    [DbContext(typeof(Tasklist25Context))]
    [Migration("20250829082907_29082025")]
    partial class _29082025
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskList_Server.Models.Priority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriorityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PriorityId");

                    b.ToTable("Priorities");
                });

            modelBuilder.Entity("TaskList_Server.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("TaskList_Server.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("DelegatedTo")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IntDisplayNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("SeriousBug")
                        .HasColumnType("bit");

                    b.Property<bool?>("SmallBug")
                        .HasColumnType("bit");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TaskList_Server.Models.TasksOld", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelegatedTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SeriousBug")
                        .HasColumnType("bit");

                    b.Property<bool>("SmallBug")
                        .HasColumnType("bit");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("TaskId");

                    b.ToTable("TasksOlds");
                });

            modelBuilder.Entity("TaskList_Server.Models.TblAdmin", b =>
                {
                    b.Property<int>("IntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntId"));

                    b.Property<string>("ChrFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChrLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChrPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChrUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DtLastLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("IntId");

                    b.ToTable("TblAdmins");
                });

            modelBuilder.Entity("TaskList_Server.Models.TblApplication", b =>
                {
                    b.Property<int>("IntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntId"));

                    b.Property<string>("ChrApplicationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IntCustomerId")
                        .HasColumnType("int");

                    b.Property<string>("testColm")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntId");

                    b.ToTable("TblApplications");
                });

            modelBuilder.Entity("TaskList_Server.Models.TblCustomer", b =>
                {
                    b.Property<int>("IntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntId"));

                    b.Property<string>("ChrCustomerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChrCustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntId");

                    b.ToTable("TblCustomers");
                });

            modelBuilder.Entity("TaskList_Server.Models.TblPermission", b =>
                {
                    b.Property<int>("IntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntId"));

                    b.Property<string>("ChrPermission")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntId");

                    b.ToTable("TblPermissions");
                });

            modelBuilder.Entity("TaskList_Server.Models.TblUploadedFile", b =>
                {
                    b.Property<int>("IntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntId"));

                    b.Property<string>("ChrOriginalFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChrSavedFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntTaskId")
                        .HasColumnType("int");

                    b.HasKey("IntId");

                    b.ToTable("TblUploadedFiles");
                });

            modelBuilder.Entity("TaskList_Server.Models.TraceMarch", b =>
                {
                    b.Property<int>("RowNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowNumber"));

                    b.Property<string>("ApplicationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BinaryData")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("ClientProcessId")
                        .HasColumnType("int");

                    b.Property<int?>("Cpu")
                        .HasColumnType("int");

                    b.Property<int?>("DatabaseId")
                        .HasColumnType("int");

                    b.Property<string>("DatabaseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Duration")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Error")
                        .HasColumnType("int");

                    b.Property<int?>("EventClass")
                        .HasColumnType("int");

                    b.Property<long?>("EventSequence")
                        .HasColumnType("bigint");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("HostName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IntegerData")
                        .HasColumnType("int");

                    b.Property<int?>("IsSystem")
                        .HasColumnType("int");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("LoginSid")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NtdomainName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NtuserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Reads")
                        .HasColumnType("bigint");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<long?>("RowCounts")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionLoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Spid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TextData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Writes")
                        .HasColumnType("bigint");

                    b.Property<long?>("XactSequence")
                        .HasColumnType("bigint");

                    b.HasKey("RowNumber");

                    b.ToTable("TraceMarches");
                });

            modelBuilder.Entity("TaskList_Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool?>("BitShowUser")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IntCustomerId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Maccess")
                        .HasColumnType("int");

                    b.Property<string>("PassWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
